#!/usr/bin/env ucode
//
//  openstream-render.uc
//  OpenStream Engine 2.1 — ucode Fast Configuration Renderer
//
//  Высокопроизводительный C-интерпретируемый скрипт для мгновенной генерации
//  конфигураций dnsmasq и правил nftables без накладных расходов shell/awk/lua.
//
//  Семантика nftables, критичная для этого файла:
//  * `redirect` — NAT-statement, допустим ТОЛЬКО в цепочке `type nat`.
//  * `reject`   — допустим ТОЛЬКО в хуках input/forward/output.
//  * `tproxy`   — допустим только в `type filter hook prerouting`, и при наличии
//                 `ip daddr` требует явного квалификатора семейства (`tproxy ip`).
//  Нарушение любого правила приводит к отказу загрузки ВСЕГО файла `nft -f`.
//
//  ВАЖНО про регулярные выражения: рантайм ucode НЕ принимает экранированный
//  дефис (`\-`) внутри класса символов, хотя проверка `ucode -c` это пропускает.
//  Во всех классах дефис размещён последним и не экранируется.
//

'use strict';

// Модуль `fs` экспортирует lsdir(); функции `dir` в нём нет.
import { readfile, writefile, access, lsdir, mkdir } from 'fs';
import { cursor } from 'uci';

let uci = cursor();
let enabled = uci.get('openstream', 'main', 'enabled') || '1';

if (enabled != '1') {
	warn('OpenStream Engine is disabled in /etc/config/openstream\n');
	exit(0);
}

let rules_dir = '/etc/openstream/rules';
let dnsmasq_out = '/tmp/dnsmasq.d/openstream-rules.conf';
let nft_out = '/tmp/openstream.nft';

// Метки должны совпадать с константами в crates/openstream-backend-openwrt/src/nftables.rs
const FWMARK_MASK = '0x00ff0000';
const FWMARK_BASE = '0x00880000';
const TPROXY_MARK = '0x00880001';
const TPROXY_PORT = 10888;
const STREAMPROXY_PORT = 8888;
const ZAPRET_QNUM = 1088;

mkdir('/tmp/dnsmasq.d');

let dns_buf = "# Auto-generated by openstream-render.uc (ucode)\n";
let nft_buf = "# Auto-generated by openstream-render.uc (ucode)\n";

// Проверка доступности IPv6 в ядре системы (#73, #91)
let ipv6_available = access('/proc/sys/net/ipv6');

// --------------------------------------------------------------- Валидация

// Строгая проверка IPv4-адреса или IPv4 CIDR. Значения приходят из UCI/LuCI и
// подставляются в nft-файл: некорректный элемент ломает загрузку всей таблицы.
function valid_ipv4_element(value) {
	let parts = split(value, '/');
	if (length(parts) > 2) return false;

	if (length(parts) == 2) {
		let plen = int(parts[1]);
		// int() вернёт 0 и для "abc", поэтому сверяем строковое представление
		if (parts[1] != sprintf('%d', plen) || plen < 0 || plen > 32) return false;
	}

	let octets = split(parts[0], '.');
	if (length(octets) != 4) return false;
	for (let o in octets) {
		if (!match(o, /^[0-9]{1,3}$/)) return false;
		let n = int(o);
		if (n < 0 || n > 255) return false;
	}
	return true;
}

function filter_valid_elements(values) {
	let out = [];
	for (let v in values) {
		let t = trim(v);
		if (length(t) > 0 && valid_ipv4_element(t)) push(out, t);
	}
	return out;
}

// UCI может вернуть строку (option) вместо массива (list) — нормализуем.
function as_list(value) {
	if (value == null) return [];
	if (type(value) == 'array') return value;
	return [value];
}

// --------------------------------------------------------- Чтение настроек

let torrent_bypass = uci.get('openstream', 'routing', 'torrent_bypass');
if (torrent_bypass == null) torrent_bypass = '1';

let bypass_cidrs = filter_valid_elements(as_list(uci.get('openstream', 'routing', 'bypass_cidrs')));
let bypass_clients = filter_valid_elements(as_list(uci.get('openstream', 'routing', 'bypass_clients')));
let dns_hosts = as_list(uci.get('openstream', 'dns', 'hosts'));

// ------------------------------------------------- Сбор доменов из правил

let sets_needed = { bypass: true, zapret2: false, streamproxy: false, vpn: false };
let rule_lines = [];

let entries = lsdir(rules_dir);
if (entries) {
	for (let filename in entries) {
		if (!match(filename, /\.osrule\.ya?ml$/)) continue;

		let content = readfile(rules_dir + '/' + filename);
		if (!content || match(content, /enabled:\s*false/)) continue;

		let is_bypass = match(content, /action:\s*"?bypass/) || match(content, /action:\s*"?pass/) || match(content, /action:\s*"?exclude/);
		let is_zapret = match(content, /zapret2/) || match(content, /nfqws2/);
		let is_streamproxy = match(content, /streamproxy/) || match(content, /stream_proxy/);
		let is_block = match(content, /action:\s*"?block/);

		for (let line in split(content, '\n')) {
			let dom_m = match(line, /-\s*["']?([a-zA-Z0-9_.*-]+)["']?/);
			if (!dom_m) continue;
			if (index(line, 'group:') >= 0 || index(line, 'id:') >= 0 ||
			    index(line, 'preset:') >= 0 || index(line, 'action:') >= 0) continue;

			let clean = lc(trim(replace(dom_m[1], /^\*\.?/, '')));
			// Строгая валидация RFC: предотвращает инъекции управляющих символов
			// и директив в конфигурацию dnsmasq.
			if (!match(clean, /^[a-z0-9.-]+$/) || index(clean, '..') >= 0 ||
			    length(clean) < 3 || length(clean) > 253 || index(clean, '.') < 0) continue;

			if (is_block) {
				if (ipv6_available) {
					push(rule_lines, sprintf("address=/%s/0.0.0.0\naddress=/%s/::", clean, clean));
				} else {
					push(rule_lines, sprintf("address=/%s/0.0.0.0", clean));
				}
			} else if (is_bypass) {
				push(rule_lines, sprintf("nftset=/%s/4#inet#openstream#bypass_targets", clean));
			} else if (is_zapret) {
				sets_needed.zapret2 = true;
				push(rule_lines, sprintf("nftset=/%s/4#inet#openstream#zapret2_targets", clean));
			} else if (is_streamproxy) {
				sets_needed.streamproxy = true;
				push(rule_lines, sprintf("nftset=/%s/4#inet#openstream#streamproxy_targets", clean));
			} else {
				sets_needed.vpn = true;
				push(rule_lines, sprintf("nftset=/%s/4#inet#openstream#vpn_default", clean));
			}
		}
	}
}

// Статические переопределения DNS (Predefined hosts — решение #60)
for (let h in dns_hosts) {
	let parts = split(trim(h), ' ');
	if (length(parts) >= 2) {
		let domain = lc(parts[0]);
		let ip = parts[1];
		if (match(domain, /^[a-z0-9.-]+$/) && match(ip, /^[0-9a-fA-F.:]+$/)) {
			dns_buf += sprintf("address=/%s/%s\n", domain, ip);
		}
	}
}

for (let l in rule_lines) {
	dns_buf += l + "\n";
}

// ------------------------------------------------------------ Генерация nft

// Идемпотентное обновление таблицы inet openstream без сброса динамических сетов (M4).
// Не затрагивает inet zapret, inet fw4 и inet openstream_divert.
nft_buf += "add table inet openstream\n";
if (sets_needed.streamproxy) {
	nft_buf += "add chain inet openstream nat_prerouting { type nat hook prerouting priority dstnat - 5; policy accept; }\n";
	nft_buf += "flush chain inet openstream nat_prerouting\n";
}
nft_buf += "add chain inet openstream mangle_prerouting { type filter hook prerouting priority mangle - 5; policy accept; }\n";
nft_buf += "flush chain inet openstream mangle_prerouting\n";
nft_buf += "add chain inet openstream openstream_tproxy { type filter hook input priority filter - 1; policy accept; }\n";
nft_buf += "flush chain inet openstream openstream_tproxy\n";
nft_buf += "table inet openstream {\n";

nft_buf += "    set bypass_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
if (sets_needed.zapret2)
	nft_buf += "    set zapret2_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
if (sets_needed.streamproxy)
	nft_buf += "    set streamproxy_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
if (sets_needed.vpn)
	nft_buf += "    set vpn_default { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";

// Исключения подсетей (Bypass CIDRs — решение #88)
let cidr_elements = "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8";
for (let c in bypass_cidrs) {
	cidr_elements += ", " + c;
}
nft_buf += sprintf("    set bypass_cidrs { type ipv4_addr; flags interval; elements = { %s }; }\n", cidr_elements);

// Исключения клиентов LAN (Bypass Clients — решение #95)
let has_clients = length(bypass_clients) > 0;
if (has_clients) {
	nft_buf += sprintf("    set bypass_clients { type ipv4_addr; flags interval; elements = { %s }; }\n",
		join(", ", bypass_clients));
}

// Прямой пропуск BitTorrent / P2P (решение #72)
if (torrent_bypass == '1') {
	nft_buf += "    set bypass_p2p_ports { type inet_service; flags interval; elements = { 6881-6889, 51413 }; }\n";
}
nft_buf += "\n";

// Общие правила исключений, повторяемые в каждой цепочке.
let bypass_prelude = "";
if (has_clients) bypass_prelude += "        ip saddr @bypass_clients return\n";
bypass_prelude += "        ip daddr @bypass_targets return\n";
bypass_prelude += "        ip daddr @bypass_cidrs return\n";

// NAT-цепочка: redirect допустим только здесь.
if (sets_needed.streamproxy) {
	nft_buf += "    chain nat_prerouting {\n";
	nft_buf += "        type nat hook prerouting priority dstnat - 5; policy accept;\n";
	nft_buf += sprintf("        meta mark & %s == %s return\n", FWMARK_MASK, FWMARK_BASE);
	nft_buf += bypass_prelude;
	nft_buf += sprintf("        ip daddr @streamproxy_targets tcp dport { 80, 443 } redirect to :%d\n", STREAMPROXY_PORT);
	nft_buf += "    }\n\n";
}

// Основная цепочка prerouting (mangle): маркировка, NFQUEUE, TPROXY.
nft_buf += "    chain mangle_prerouting {\n";
nft_buf += "        type filter hook prerouting priority mangle - 5; policy accept;\n";
// Трафик самого sing-box исключаем по метке, иначе петля (#74).
nft_buf += sprintf("        meta mark & %s == %s return\n", FWMARK_MASK, FWMARK_BASE);
nft_buf += "        meta l4proto { tcp, udp } iif lo return\n";
nft_buf += bypass_prelude;

if (torrent_bypass == '1') {
	nft_buf += "        th dport @bypass_p2p_ports return\n";
}

if (sets_needed.zapret2) {
	nft_buf += sprintf("        ip daddr @zapret2_targets tcp flags syn / syn,rst,ack queue num %d bypass\n", ZAPRET_QNUM);
}

if (sets_needed.vpn) {
	// Квалификатор `tproxy ip` обязателен: правило содержит `ip daddr`, и без
	// указания семейства nft отвергает загрузку всего файла.
	nft_buf += sprintf("        ip daddr @vpn_default meta l4proto { tcp, udp } tproxy ip to :%d meta mark set %s\n",
		TPROXY_PORT, TPROXY_MARK);
}
nft_buf += "    }\n";

// Цепочка openstream_tproxy для разрешения сокетов локальных прокси в изолированных
// зонах fw4 (решение #84).
nft_buf += "\n    chain openstream_tproxy {\n";
nft_buf += "        type filter hook input priority filter - 1; policy accept;\n";
nft_buf += sprintf("        meta mark & %s == %s accept\n", FWMARK_MASK, FWMARK_BASE);
nft_buf += sprintf("        iif lo tcp dport { %d, %d } accept\n", STREAMPROXY_PORT, ZAPRET_QNUM);
nft_buf += sprintf("        iif lo udp dport { %d, %d } accept\n", STREAMPROXY_PORT, ZAPRET_QNUM);
nft_buf += "    }\n";

nft_buf += "}\n";

writefile(dnsmasq_out, dns_buf);
writefile(nft_out, nft_buf);

print("✓ OpenStream configurations rendered successfully via ucode.\n");
