#!/usr/bin/env ucode
//
//  openstream-render.uc
//  OpenStream Engine 2.1 — ucode Fast Configuration Renderer
//
//  Высокопроизводительный C-интерпретируемый скрипт для мгновенной генерации
//  конфигураций dnsmasq и правил nftables без накладных расходов shell/awk/lua.
//

'use strict';

import { readfile, writefile, access, dir, mkdir } from 'fs';
import { cursor } from 'uci';

let uci = cursor();
let enabled = uci.get('openstream', 'main', 'enabled') || '1';

if (enabled != '1') {
	warn('OpenStream Engine is disabled in /etc/config/openstream\n');
	exit(0);
}

let rules_dir = '/etc/openstream/rules';
let dnsmasq_out = '/tmp/dnsmasq.d/openstream-rules.conf';
let nft_out = '/tmp/openstream.nft';

mkdir('/tmp/dnsmasq.d');

let dns_buf = "# Auto-generated by openstream-render.uc (ucode)\n";
let nft_buf = "# Auto-generated by openstream-render.uc (ucode)\n";

// Атомарное обновление таблицы inet openstream (не затрагивает inet zapret, inet fw4)
nft_buf += "table inet openstream\n";
nft_buf += "delete table inet openstream\n";
nft_buf += "table inet openstream {\n";
nft_buf += "    set zapret2_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set streamproxy_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set vpn_default { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set bypass_cidrs { type ipv4_addr; flags interval; elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 }; }\n";
nft_buf += "    set bypass_p2p_ports { type inet_service; elements = { 6881-6889, 51413 }; }\n\n";

nft_buf += "    chain openstream_tproxy {\n";
nft_buf += "        type filter hook input priority filter - 1; policy accept;\n";
nft_buf += "        meta mark & 0x00ff0000 == 0x00880000 accept\n";
nft_buf += "    }\n\n";

nft_buf += "    chain mangle_prerouting {\n";
nft_buf += "        type filter hook prerouting priority mangle - 5; policy accept;\n";
nft_buf += "        ct mark & 0x00ff0000 == 0x00880000 return\n";
nft_buf += "        ip daddr @bypass_cidrs return\n";
nft_buf += "        th dport @bypass_p2p_ports return\n";
nft_buf += "        ip daddr @zapret2_targets tcp flags syn queue num 1088 bypass\n";
nft_buf += "        ip daddr @streamproxy_targets tcp dport { 80, 443 } redirect to :8888\n";
nft_buf += "        ip daddr @vpn_default mark set 0x00880001\n";
nft_buf += "    }\n";
nft_buf += "}\n";

let entries = dir(rules_dir);
if (entries) {
	for (let filename in entries) {
		if (match(filename, /\.osrule\.ya?ml$/)) {
			let content = readfile(rules_dir + '/' + filename);
			if (!content || match(content, /enabled:\s*false/)) continue;

			let is_zapret = match(content, /zapret2/);
			let is_streamproxy = match(content, /streamproxy/) || match(content, /stream_proxy/);
			let is_block = match(content, /action:\s*"?block/);

			for (let line in split(content, '\n')) {
				let dom_m = match(line, /-\s*["']?([a-zA-Z0-9_\-\.\*]+)["']?/);
				if (dom_m && index(line, 'group:') < 0 && index(line, 'id:') < 0 && index(line, 'preset:') < 0) {
					let raw_dom = dom_m[1];
					let clean = replace(raw_dom, /^\*\.?/, '');
					clean = lc(trim(clean));
					// Строгая валидация RFC: предотвращает инъекции любых управляющих символов и директив в dnsmasq
					if (match(clean, /^[a-z0-9\.\-]+$/) && index(clean, '..') < 0 && length(clean) >= 3 && length(clean) <= 253 && index(clean, '.') >= 0) {
						if (is_block) {
							dns_buf += sprintf("address=/%s/0.0.0.0\naddress=/%s/::\n", clean, clean);
						} else if (is_zapret) {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#zapret2_targets\n", clean);
						} else if (is_streamproxy) {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#streamproxy_targets\n", clean);
						} else {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#vpn_default\n", clean);
						}
					}
				}
			}
		}
	}
}

writefile(dnsmasq_out, dns_buf);
writefile(nft_out, nft_buf);

print("✓ OpenStream configurations rendered successfully via ucode.\n");
