#!/usr/bin/env ucode
//
//  openstream-render.uc
//  OpenStream Engine 2.1 — ucode Fast Configuration Renderer
//
//  Высокопроизводительный C-интерпретируемый скрипт для мгновенной генерации
//  конфигураций dnsmasq и правил nftables без накладных расходов shell/awk/lua.
//

'use strict';

import { readfile, writefile, access, dir, mkdir } from 'fs';
import { cursor } from 'uci';

let uci = cursor();
let enabled = uci.get('openstream', 'main', 'enabled') || '1';

if (enabled != '1') {
	warn('OpenStream Engine is disabled in /etc/config/openstream\n');
	exit(0);
}

let rules_dir = '/etc/openstream/rules';
let dnsmasq_out = '/tmp/dnsmasq.d/openstream-rules.conf';
let nft_out = '/tmp/openstream.nft';

mkdir('/tmp/dnsmasq.d');

let dns_buf = "# Auto-generated by openstream-render.uc (ucode)\n";
let nft_buf = "# Auto-generated by openstream-render.uc (ucode)\n";

// Проверка доступности IPv6 в ядре системы (#73, #91)
let ipv6_available = access('/proc/sys/net/ipv6');

// Чтение настроек маршрутизации и безопасности
let torrent_bypass = uci.get('openstream', 'routing', 'torrent_bypass');
if (torrent_bypass == null) torrent_bypass = '1';

let bypass_cidrs = uci.get('openstream', 'routing', 'bypass_cidrs') || [];
let bypass_clients = uci.get('openstream', 'routing', 'bypass_clients') || [];
let dns_hosts = uci.get('openstream', 'dns', 'hosts') || [];

// Атомарное обновление таблицы inet openstream (не затрагивает inet zapret, inet fw4)
nft_buf += "table inet openstream\n";
nft_buf += "delete table inet openstream\n";
nft_buf += "table inet openstream {\n";
nft_buf += "    set zapret2_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set streamproxy_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set vpn_default { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";
nft_buf += "    set bypass_targets { type ipv4_addr; flags interval, timeout; timeout 1d; size 65536; }\n";

// Исключения подсетей (Bypass CIDRs - решение #88)
let cidr_elements = "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8";
for (let c in bypass_cidrs) {
	let trimmed = trim(c);
	if (length(trimmed) > 0) {
		cidr_elements += ", " + trimmed;
	}
}
nft_buf += sprintf("    set bypass_cidrs { type ipv4_addr; flags interval; elements = { %s }; }\n", cidr_elements);

// Исключения клиентов LAN (Bypass Clients - решение #95)
if (length(bypass_clients) > 0) {
	let client_elements = "";
	for (let i, cl in bypass_clients) {
		let trimmed = trim(cl);
		if (length(trimmed) > 0) {
			if (i > 0) client_elements += ", ";
			client_elements += trimmed;
		}
	}
	if (length(client_elements) > 0) {
		nft_buf += sprintf("    set bypass_clients { type ipv4_addr; flags interval; elements = { %s }; }\n", client_elements);
	}
}

// Прямой пропуск BitTorrent / P2P (решение #72)
if (torrent_bypass == '1') {
	nft_buf += "    set bypass_p2p_ports { type inet_service; elements = { 6881-6889, 51413 }; }\n";
}
nft_buf += "\n";

// Цепочка openstream_tproxy для разрешения сокетов в гостевых и изолированных зонах fw4 (решение #84)
nft_buf += "    chain openstream_tproxy {\n";
nft_buf += "        type filter hook input priority filter - 1; policy accept;\n";
nft_buf += "        meta mark & 0x00ff0000 == 0x00880000 accept\n";
nft_buf += "        tcp dport { 8888, 1088 } accept\n";
nft_buf += "        udp dport { 8888, 1088 } accept\n";
nft_buf += "    }\n\n";

// Основная цепочка prerouting
nft_buf += "    chain mangle_prerouting {\n";
nft_buf += "        type filter hook prerouting priority mangle - 5; policy accept;\n";
nft_buf += "        ct mark & 0x00ff0000 == 0x00880000 return\n";

if (length(bypass_clients) > 0) {
	nft_buf += "        ip saddr @bypass_clients return\n";
}

nft_buf += "        ip daddr @bypass_targets return\n";
nft_buf += "        ip daddr @bypass_cidrs return\n";

if (torrent_bypass == '1') {
	nft_buf += "        th dport @bypass_p2p_ports return\n";
}

nft_buf += "        ip daddr @zapret2_targets tcp flags syn queue num 1088 bypass\n";
nft_buf += "        ip daddr @streamproxy_targets tcp dport { 80, 443 } redirect to :8888\n";
nft_buf += "        ip daddr @vpn_default mark set 0x00880001\n";
nft_buf += "    }\n";
nft_buf += "}\n";

// Статические переопределения DNS (Predefined hosts - решение #60)
for (let h in dns_hosts) {
	let parts = split(trim(h), ' ');
	if (length(parts) >= 2) {
		let domain = lc(parts[0]);
		let ip = parts[1];
		if (match(domain, /^[a-z0-9\.\-]+$/) && match(ip, /^[0-9\.\:]+$/)) {
			dns_buf += sprintf("address=/%s/%s\n", domain, ip);
		}
	}
}

let entries = dir(rules_dir);
if (entries) {
	for (let filename in entries) {
		if (match(filename, /\.osrule\.ya?ml$/)) {
			let content = readfile(rules_dir + '/' + filename);
			if (!content || match(content, /enabled:\s*false/)) continue;

			let is_bypass = match(content, /action:\s*"?bypass/) || match(content, /action:\s*"?pass/) || match(content, /action:\s*"?exclude/);
			let is_zapret = match(content, /zapret2/) || match(content, /nfqws2/);
			let is_streamproxy = match(content, /streamproxy/) || match(content, /stream_proxy/);
			let is_block = match(content, /action:\s*"?block/);

			for (let line in split(content, '\n')) {
				let dom_m = match(line, /-\s*["']?([a-zA-Z0-9_\-\.\*]+)["']?/);
				if (dom_m && index(line, 'group:') < 0 && index(line, 'id:') < 0 && index(line, 'preset:') < 0 && index(line, 'action:') < 0) {
					let raw_dom = dom_m[1];
					let clean = replace(raw_dom, /^\*\.?/, '');
					clean = lc(trim(clean));
					// Строгая валидация RFC: предотвращает инъекции любых управляющих символов и директив в dnsmasq
					if (match(clean, /^[a-z0-9\.\-]+$/) && index(clean, '..') < 0 && length(clean) >= 3 && length(clean) <= 253 && index(clean, '.') >= 0) {
						if (is_block) {
							if (ipv6_available) {
								dns_buf += sprintf("address=/%s/0.0.0.0\naddress=/%s/::\n", clean, clean);
							} else {
								dns_buf += sprintf("address=/%s/0.0.0.0\n", clean);
							}
						} else if (is_bypass) {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#bypass_targets\n", clean);
						} else if (is_zapret) {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#zapret2_targets\n", clean);
						} else if (is_streamproxy) {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#streamproxy_targets\n", clean);
						} else {
							dns_buf += sprintf("nftset=/%s/4#inet#openstream#vpn_default\n", clean);
						}
					}
				}
			}
		}
	}
}

writefile(dnsmasq_out, dns_buf);
writefile(nft_out, nft_buf);

print("✓ OpenStream configurations rendered successfully via ucode.\n");
