use std::collections::BTreeSet;
use openstream_core::CompiledRuleSet;

/// Санирование домена для безопасного использования в конфигурации dnsmasq
pub fn sanitize_domain(domain: &str) -> Option<String> {
    let clean = domain
        .trim()
        .trim_start_matches('*')
        .trim_start_matches('.')
        .trim_end_matches('.')
        .to_ascii_lowercase();

    if clean.is_empty() {
        return None;
    }

    // Защита от инъекций директив: разрешены только a-z, 0-9, '-', '.'
    if clean.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.') {
        Some(clean)
    } else {
        None
    }
}

/// Генерация конфигурационного файла для dnsmasq (/tmp/dnsmasq.d/openstream-rules.conf)
pub fn generate_dnsmasq_config(compiled: &CompiledRuleSet, nft_table_family: &str, nft_table_name: &str) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("# Auto-generated by OpenStream Engine 2.0 (openstream-backend-openwrt)\n");
    out.push_str("# Do NOT edit manually; changes will be overwritten.\n\n");

    // 1. Блокируемые домены (DNS Sinkhole: 0.0.0.0 и ::)
    if !compiled.blocked_domains.is_empty() {
        out.push_str("# --- DNS Sinkhole (Block) ---\n");
        let mut seen = BTreeSet::new();
        for d in &compiled.blocked_domains {
            if let Some(clean) = sanitize_domain(d) {
                if seen.insert(clean.clone()) {
                    out.push_str(&format!("address=/{}/0.0.0.0\n", clean));
                    out.push_str(&format!("address=/{}/::\n", clean));
                }
            }
        }
        out.push('\n');
    }

    // 2. Домены с переопределением DNS (SmartDNS / DnsOverride)
    if !compiled.dns_overrides.is_empty() {
        out.push_str("# --- DNS Overrides (SmartDNS) ---\n");
        for (d, ips) in &compiled.dns_overrides {
            if let Some(clean) = sanitize_domain(d) {
                for ip in ips {
                    out.push_str(&format!("address=/{}/{}\n", clean, ip));
                }
            }
        }
        out.push('\n');
    }

    // 3. Домены для проксирования (Proxy Gateways) через nftset
    if !compiled.proxy_domains.is_empty() {
        out.push_str("# --- Proxy Routing (nftset) ---\n");
        let mut seen = BTreeSet::new();
        for (d, gw_id) in &compiled.proxy_domains {
            if let Some(clean) = sanitize_domain(d) {
                let clean_gw: String = gw_id
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                let set_name = if clean_gw.is_empty() {
                    "vpn_default".to_string()
                } else {
                    format!("vpn_{}", clean_gw)
                };

                let key = (clean.clone(), set_name.clone());
                if seen.insert(key) {
                    out.push_str(&format!(
                        "nftset=/{}/4#{}#{}#{}\n",
                        clean, nft_table_family, nft_table_name, set_name
                    ));
                }
            }
        }
        out.push('\n');
    }

    // 4. Домены для Zapret2 (NFQUEUE 1088 - решение #85)
    if !compiled.zapret2_domains.is_empty() {
        out.push_str("# --- Zapret2 Targets (nftset) ---\n");
        let mut seen = BTreeSet::new();
        for (d, _) in &compiled.zapret2_domains {
            if let Some(clean) = sanitize_domain(d) {
                if seen.insert(clean.clone()) {
                    out.push_str(&format!(
                        "nftset=/{}/4#{}#{}#zapret2_targets\n",
                        clean, nft_table_family, nft_table_name
                    ));
                }
            }
        }
        out.push('\n');
    }

    // 5. Домены для OpenStream StreamProxy (127.0.0.1:8888)
    if !compiled.streamproxy_domains.is_empty() {
        out.push_str("# --- StreamProxy Targets (nftset) ---\n");
        let mut seen = BTreeSet::new();
        for d in &compiled.streamproxy_domains {
            if let Some(clean) = sanitize_domain(d) {
                if seen.insert(clean.clone()) {
                    out.push_str(&format!(
                        "nftset=/{}/4#{}#{}#streamproxy_targets\n",
                        clean, nft_table_family, nft_table_name
                    ));
                }
            }
        }
        out.push('\n');
    }

    // 6. Домены для локальной десинхронизации (Anti-DPI / DpiEvasiveDirect)
    if !compiled.dpi_evasive_domains.is_empty() {
        out.push_str("# --- Anti-DPI Desync (nftset) ---\n");
        let mut seen = BTreeSet::new();
        for d in &compiled.dpi_evasive_domains {
            if let Some(clean) = sanitize_domain(d) {
                if seen.insert(clean.clone()) {
                    out.push_str(&format!(
                        "nftset=/{}/4#{}#{}#dpi_evasive\n",
                        clean, nft_table_family, nft_table_name
                    ));
                }
            }
        }
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::IpAddr;

    #[test]
    fn test_sanitize_domain() {
        assert_eq!(sanitize_domain("*.live-video.net"), Some("live-video.net".into()));
        assert_eq!(sanitize_domain(".twitch.tv"), Some("twitch.tv".into()));
        assert_eq!(sanitize_domain("gql.twitch.tv."), Some("gql.twitch.tv".into()));
        assert_eq!(sanitize_domain("invalid domain/with/slash"), None);
        assert_eq!(sanitize_domain("newline\ninjection.com"), None);
    }

    #[test]
    fn test_generate_dnsmasq_config() {
        let mut compiled = CompiledRuleSet::default();
        compiled.blocked_domains.push("edge.ads.twitch.tv".into());
        compiled.dns_overrides.push((
            "usher.ttvnw.net".into(),
            vec!["1.2.3.4".parse::<IpAddr>().unwrap()],
        ));
        compiled.proxy_domains.push(("gql.twitch.tv".into(), "clean_al".into()));
        compiled.dpi_evasive_domains.push("*.googlevideo.com".into());

        let conf = generate_dnsmasq_config(&compiled, "inet", "openstream");

        assert!(conf.contains("address=/edge.ads.twitch.tv/0.0.0.0"));
        assert!(conf.contains("address=/usher.ttvnw.net/1.2.3.4"));
        assert!(conf.contains("nftset=/gql.twitch.tv/4#inet#openstream#vpn_clean_al"));
        assert!(conf.contains("nftset=/googlevideo.com/4#inet#openstream#dpi_evasive"));
    }
}
