//
//  nftables.rs
//  openstream-backend-openwrt
//
//  Генератор конфигурации nftables для OpenStream Engine 2.0:
//  - Изоляция меток ct mark (0x00880000) без конфликтов с mwan3 (#87)
//  - Строгая сепарация трафика Zapret2 от VPN-шлюзов для исключения PR_CONNECT_RESET (#2)
//  - Защита от петель маршрутизации и переполнения conntrack (#74)
//  - Поддержка исключений IP/CIDR (bypass_cidrs) (#88)
//  - Отсечение P2P/BitTorrent (bypass_p2p) напрямую в WAN (#72)
//  - Совместимость с гостевыми зонами fw4 при input=REJECT (#84)
//  - Двухстековый контроль inet с graceful деградацией (#91)
//

use std::collections::BTreeSet;
use openstream_core::CompiledRuleSet;

pub const OPENSTREAM_FWMARK_BASE: u32 = 0x00880000;
pub const OPENSTREAM_FWMARK_MASK: u32 = 0x00ff0000;
pub const OPENSTREAM_ZAPRET_QNUM: u16 = 1088;

/// Генерация комплексной конфигурации таблицы inet openstream
pub fn generate_nftables_rules(compiled: &CompiledRuleSet, table_family: &str, table_name: &str) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("# Auto-generated by OpenStream Engine 2.0 (Orchestrator)\n");
    out.push_str(&format!("table {} {}\n", table_family, table_name));
    out.push_str(&format!("delete table {} {}\n", table_family, table_name));
    out.push_str(&format!("table {} {} {{\n", table_family, table_name));

    // 1. Динамические и статические сеты
    out.push_str("    # Исключения из маршрутизации (Bypass CIDRs - решение #88)\n");
    out.push_str("    set bypass_cidrs {\n        type ipv4_addr\n        flags interval\n");
    out.push_str("        elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8");
    for cidr in &compiled.bypass_cidrs {
        out.push_str(&format!(", {}", cidr));
    }
    out.push_str(" }\n    }\n\n");

    if compiled.bypass_p2p {
        out.push_str("    # Исключение BitTorrent/P2P портов (решение #72)\n");
        out.push_str("    set bypass_p2p_ports {\n        type inet_service\n        elements = { 6881-6889, 51413 }\n    }\n\n");
    }

    // Сет для Zapret2 (NFQUEUE 1088)
    if !compiled.zapret2_domains.is_empty() {
        out.push_str("    set zapret2_targets {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n\n");
    }

    // Сет для StreamProxy (127.0.0.1:8888)
    if !compiled.streamproxy_domains.is_empty() {
        out.push_str("    set streamproxy_targets {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n\n");
    }

    // Сет для встроенного Anti-DPI
    if !compiled.dpi_evasive_domains.is_empty() {
        out.push_str("    set dpi_evasive {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n\n");
    }

    // Сеты для VPN-шлюзов
    let mut vpn_sets = BTreeSet::new();
    for (_, gw_id) in &compiled.proxy_domains {
        let clean_gw: String = gw_id
            .chars()
            .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        let set_name = if clean_gw.is_empty() {
            "vpn_default".to_string()
        } else {
            format!("vpn_{}", clean_gw)
        };
        vpn_sets.insert(set_name);
    }

    for set_name in &vpn_sets {
        out.push_str(&format!(
            "    set {} {{\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }}\n",
            set_name
        ));
    }

    // 2. Цепочка openstream_tproxy для разрешения сокетов в гостевых зонах fw4 (решение #84)
    out.push_str("\n    # Защита сокетов в изолированных и гостевых сетях fw4 (решение #84)\n");
    out.push_str("    chain openstream_tproxy {\n");
    out.push_str("        type filter hook input priority filter - 1; policy accept;\n");
    out.push_str("        meta mark & 0x00ff0000 == 0x00880000 accept\n");
    out.push_str("    }\n");

    // 3. Основная цепочка mangle prerouting
    out.push_str("\n    # Маршрутизация и диспетчеризация трафика\n");
    out.push_str("    chain mangle_prerouting {\n");
    out.push_str("        type filter hook prerouting priority mangle - 5; policy accept;\n\n");

    out.push_str("        # Защита от петель зацикливания и conntrack exhaustion (решение #74)\n");
    out.push_str("        ct mark & 0x00ff0000 == 0x00880000 return\n\n");

    out.push_str("        # Исключения подсетей (Bypass CIDRs - решение #88)\n");
    out.push_str("        ip daddr @bypass_cidrs return\n");

    if compiled.bypass_p2p {
        out.push_str("        # Исключение BitTorrent напрямую в WAN (решение #72)\n");
        out.push_str("        th dport @bypass_p2p_ports return\n");
    }

    // Сепарация Zapret2: направляем в NFQUEUE до туннелей (решение #2)
    if !compiled.zapret2_domains.is_empty() {
        out.push_str("\n        # Направление в Zapret2 NFQUEUE без повреждения VPN-пакетов (решение #2, #85)\n");
        out.push_str(&format!(
            "        ip daddr @zapret2_targets tcp flags syn queue num {} bypass\n",
            OPENSTREAM_ZAPRET_QNUM
        ));
    }

    // Направление в StreamProxy
    if !compiled.streamproxy_domains.is_empty() {
        out.push_str("\n        # Перенаправление в OpenStream StreamProxy\n");
        out.push_str("        ip daddr @streamproxy_targets tcp dport { 80, 443 } redirect to :8888\n");
    }

    // Метки для VPN-туннелей
    let mut mark_idx = 1;
    for set_name in &vpn_sets {
        let fwmark = OPENSTREAM_FWMARK_BASE | mark_idx;
        out.push_str(&format!(
            "        ip daddr @{} mark set {:#x}\n",
            set_name, fwmark
        ));
        mark_idx += 1;
    }

    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Для обратной совместимости с тестами и модулями
pub fn generate_nftables_sets(compiled: &CompiledRuleSet, table_family: &str, table_name: &str) -> String {
    generate_nftables_rules(compiled, table_family, table_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_nftables_rules_comprehensive() {
        let mut compiled = CompiledRuleSet::default();
        compiled.proxy_domains.push(("beta.crunchyroll.com".into(), "us_west".into()));
        compiled.zapret2_domains.push(("googlevideo.com".into(), "youtube_4k".into()));
        compiled.streamproxy_domains.push("live-video.net".into());
        compiled.bypass_p2p = true;

        let nft = generate_nftables_rules(&compiled, "inet", "openstream");

        // Проверка базовой структуры
        assert!(nft.contains("table inet openstream {"));
        assert!(nft.contains("set bypass_cidrs {"));
        assert!(nft.contains("set bypass_p2p_ports {"));
        assert!(nft.contains("set zapret2_targets {"));
        assert!(nft.contains("set streamproxy_targets {"));
        assert!(nft.contains("set vpn_us_west {"));

        // Проверка решения багов
        assert!(nft.contains("ct mark & 0x00ff0000 == 0x00880000 return")); // Защита от петель #74
        assert!(nft.contains("openstream_tproxy")); // Гостевые сети #84
        assert!(nft.contains("queue num 1088 bypass")); // Сепарация Zapret2 #2, #85
        assert!(nft.contains("redirect to :8888")); // StreamProxy
        assert!(nft.contains("mark set 0x880001")); // Изолированная метка fwmark #87
    }
}
