//
//  nftables.rs
//  openstream-backend-openwrt
//
//  Генератор конфигурации nftables для OpenStream Engine 2.1:
//  - Изоляция меток fwmark (0x00880000/0x00ff0000) без конфликтов с mwan3 (#87)
//  - Строгая сепарация трафика Zapret2 от VPN-шлюзов для исключения PR_CONNECT_RESET (#2)
//  - Защита от петель маршрутизации через routing_mark sing-box (#74)
//  - Поддержка исключений IP/CIDR (bypass_cidrs) (#88)
//  - Отсечение P2P/BitTorrent (bypass_p2p) напрямую в WAN (#72)
//  - Двухстековый контроль inet с graceful деградацией (#91)
//
//  ВАЖНО о типах цепочек (nftables semantics):
//  - `redirect` и `dnat` — NAT-statements, допустимы ТОЛЬКО в цепочке `type nat`.
//  - `reject` допустим ТОЛЬКО в хуках input/forward/output.
//  - `tproxy` допустим только в `type filter hook prerouting`.
//  Нарушение любого из этих правил приводит к отказу загрузки ВСЕГО файла `nft -f`.
//

use openstream_core::CompiledRuleSet;
use std::collections::BTreeSet;
use std::fmt::Write as _;

pub const OPENSTREAM_FWMARK_BASE: u32 = 0x00880000;
pub const OPENSTREAM_FWMARK_MASK: u32 = 0x00ff0000;
/// Метка, по которой policy routing заворачивает пакет на loopback для TPROXY.
pub const OPENSTREAM_TPROXY_MARK: u32 = 0x00880001;
/// Метка исходящего трафика самого sing-box (`routing_mark`). Исключается из перехвата,
/// иначе возникает петля: sing-box → prerouting → tproxy → sing-box.
pub const OPENSTREAM_SINGBOX_MARK: u32 = 0x00880002;
pub const OPENSTREAM_ZAPRET_QNUM: u16 = 1088;
pub const OPENSTREAM_TPROXY_PORT: u16 = 10888;
pub const OPENSTREAM_STREAMPROXY_PORT: u16 = 8888;

/// Проверка имени сета nftables (защита от инъекций в генерируемый файл).
fn is_valid_set_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
        && name.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
}

/// Санирование идентификатора шлюза в имя сета `vpn_<id>`.
pub fn gateway_set_name(gateway_id: &str) -> String {
    let clean: String = gateway_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();

    if clean.is_empty() {
        "vpn_default".to_string()
    } else {
        format!("vpn_{}", clean)
    }
}

/// Валидация элемента сета `bypass_clients` — строго IPv4-адрес или IPv4 CIDR.
///
/// Без этой проверки некорректное значение из UCI/LuCI ломает загрузку всей таблицы.
fn is_valid_ipv4_element(value: &str) -> bool {
    let (addr_part, prefix_part) = match value.split_once('/') {
        Some((a, p)) => (a, Some(p)),
        None => (value, None),
    };

    if addr_part.parse::<std::net::Ipv4Addr>().is_err() {
        return false;
    }

    match prefix_part {
        None => true,
        Some(p) => p.parse::<u8>().is_ok_and(|len| len <= 32),
    }
}

/// Отфильтрованный список клиентов LAN, безопасный для подстановки в nft-файл.
fn valid_bypass_clients(compiled: &CompiledRuleSet) -> Vec<&str> {
    compiled
        .bypass_clients
        .iter()
        .map(|s| s.trim())
        .filter(|s| is_valid_ipv4_element(s))
        .collect()
}

/// Генерация комплексной конфигурации таблицы inet openstream.
pub fn generate_nftables_rules(
    compiled: &CompiledRuleSet,
    table_family: &str,
    table_name: &str,
) -> String {
    let mut out = String::with_capacity(8192);
    let clients = valid_bypass_clients(compiled);
    let has_clients = !clients.is_empty();

    // Набор сетов для VPN-шлюзов (дедупликация + сортировка для детерминированного вывода)
    let mut vpn_sets = BTreeSet::new();
    for (_, gw_id) in &compiled.proxy_domains {
        let set_name = gateway_set_name(gw_id);
        if is_valid_set_name(&set_name) {
            vpn_sets.insert(set_name);
        }
    }

    out.push_str("# Auto-generated by OpenStream Engine 2.1 (openstream-backend-openwrt)\n");
    out.push_str("# Не редактировать вручную — файл перезаписывается при каждом применении правил.\n\n");

    // Идемпотентное создание таблицы без сброса динамических сетов (M4).
    // add table / flush chain сохраняет накопленные dnsmasq IP-адреса в памяти.
    let _ = writeln!(out, "add table {} {}", table_family, table_name);
    if !compiled.streamproxy_domains.is_empty() {
        let _ = writeln!(
            out,
            "add chain {} {} nat_prerouting {{ type nat hook prerouting priority dstnat - 5; policy accept; }}",
            table_family, table_name
        );
        let _ = writeln!(out, "flush chain {} {} nat_prerouting", table_family, table_name);
    }
    let _ = writeln!(
        out,
        "add chain {} {} mangle_prerouting {{ type filter hook prerouting priority mangle - 5; policy accept; }}",
        table_family, table_name
    );
    let _ = writeln!(out, "flush chain {} {} mangle_prerouting", table_family, table_name);
    if compiled.disable_quic || compiled.block_doh {
        let _ = writeln!(
            out,
            "add chain {} {} filter_forward {{ type filter hook forward priority filter + 5; policy accept; }}",
            table_family, table_name
        );
        let _ = writeln!(out, "flush chain {} {} filter_forward", table_family, table_name);
    }
    let _ = writeln!(out, "table {} {} {{", table_family, table_name);

    // ---------------------------------------------------------------- Сеты

    out.push_str("    # Исключения подсетей (Bypass CIDRs — решение #88)\n");
    out.push_str("    set bypass_cidrs {\n");
    out.push_str("        type ipv4_addr\n");
    out.push_str("        flags interval\n");
    out.push_str("        elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8");
    for cidr in &compiled.bypass_cidrs {
        // bypass_cidrs имеет тип ipnet::IpNet — значение уже валидно по построению.
        if cidr.addr().is_ipv4() {
            let _ = write!(out, ", {}", cidr);
        }
    }
    out.push_str(" }\n    }\n\n");

    if has_clients {
        out.push_str("    # Исключения конкретных клиентских устройств LAN (решение #95)\n");
        out.push_str("    set bypass_clients {\n");
        out.push_str("        type ipv4_addr\n");
        out.push_str("        flags interval\n");
        let _ = writeln!(out, "        elements = {{ {} }}", clients.join(", "));
        out.push_str("    }\n\n");
    }

    if compiled.bypass_p2p {
        out.push_str("    # Исключение BitTorrent/P2P портов (решение #72)\n");
        out.push_str("    set bypass_p2p_ports {\n");
        out.push_str("        type inet_service\n");
        out.push_str("        flags interval\n");
        out.push_str("        elements = { 6881-6889, 51413 }\n    }\n\n");
    }

    // Динамические сеты наполняются dnsmasq через `nftset=` в момент DNS-резолва.
    out.push_str("    # Динамические сеты (наполняются dnsmasq при резолве доменов)\n");
    out.push_str("    set bypass_targets {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n");

    if !compiled.zapret2_domains.is_empty() {
        out.push_str("    set zapret2_targets {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n");
    }

    if !compiled.streamproxy_domains.is_empty() {
        out.push_str("    set streamproxy_targets {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n");
    }

    if !compiled.dpi_evasive_domains.is_empty() {
        out.push_str("    set dpi_evasive {\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }\n");
    }

    for set_name in &vpn_sets {
        let _ = writeln!(
            out,
            "    set {} {{\n        type ipv4_addr\n        flags interval, timeout\n        timeout 1d\n        size 65536\n    }}",
            set_name
        );
    }
    out.push('\n');

    // ------------------------------------------------- Цепочка NAT prerouting
    // `redirect` — NAT-statement, поэтому требуется отдельная цепочка type nat.
    if !compiled.streamproxy_domains.is_empty() {
        out.push_str("    # NAT-цепочка: локальное перенаправление в StreamProxy.\n");
        out.push_str("    # redirect недопустим в type filter — только здесь (type nat).\n");
        out.push_str("    chain nat_prerouting {\n");
        out.push_str("        type nat hook prerouting priority dstnat - 5; policy accept;\n");
        let _ = writeln!(
            out,
            "        meta mark & {:#010x} == {:#010x} return",
            OPENSTREAM_FWMARK_MASK, OPENSTREAM_FWMARK_BASE
        );
        if has_clients {
            out.push_str("        ip saddr @bypass_clients return\n");
        }
        out.push_str("        ip daddr @bypass_targets return\n");
        out.push_str("        ip daddr @bypass_cidrs return\n");
        let _ = writeln!(
            out,
            "        ip daddr @streamproxy_targets tcp dport {{ 80, 443 }} redirect to :{}",
            OPENSTREAM_STREAMPROXY_PORT
        );
        out.push_str("    }\n\n");
    }

    // ----------------------------------------- Цепочка mangle prerouting (TPROXY)
    out.push_str("    # Основная цепочка диспетчеризации трафика LAN → WAN.\n");
    out.push_str("    chain mangle_prerouting {\n");
    out.push_str("        type filter hook prerouting priority mangle - 5; policy accept;\n\n");

    out.push_str("        # Трафик самого sing-box (routing_mark) — исключаем, иначе петля (#74)\n");
    let _ = writeln!(
        out,
        "        meta mark & {:#010x} == {:#010x} return",
        OPENSTREAM_FWMARK_MASK, OPENSTREAM_FWMARK_BASE
    );
    out.push_str("        # Локальный и служебный трафик не перехватываем\n");
    out.push_str("        meta l4proto { tcp, udp } iif lo return\n\n");

    if has_clients {
        out.push_str("        # Прямой пропуск исключённых клиентских устройств LAN (#95)\n");
        out.push_str("        ip saddr @bypass_clients return\n");
    }

    out.push_str("        # Приоритетное исключение доменов из обработки (Bypass / Pass)\n");
    out.push_str("        ip daddr @bypass_targets return\n");
    out.push_str("        # Исключения подсетей (#88) — включая RFC1918 и loopback\n");
    out.push_str("        ip daddr @bypass_cidrs return\n");

    if compiled.exclude_ntp {
        out.push_str("        # Исключение NTP (UDP 123) для синхронизации системного времени\n");
        out.push_str("        udp dport 123 return\n");
    }

    if compiled.bypass_p2p {
        out.push_str("        # Исключение BitTorrent напрямую в WAN (решение #72)\n");
        out.push_str("        th dport @bypass_p2p_ports return\n");
    }

    if !compiled.zapret2_domains.is_empty() {
        out.push_str("\n        # Направление в Zapret2 NFQUEUE до туннелей (решение #2, #85)\n");
        let _ = writeln!(
            out,
            "        ip daddr @zapret2_targets tcp flags syn / syn,rst,ack queue num {} bypass",
            OPENSTREAM_ZAPRET_QNUM
        );
    }

    if !vpn_sets.is_empty() {
        out.push_str("\n        # Перехват в TPROXY-сокет sing-box с изолированной меткой (#87)\n");
        out.push_str("        # Требует policy routing: ip rule fwmark <mark> lookup <table>\n");
        out.push_str("        # Квалификатор `tproxy ip` обязателен: правило содержит `ip daddr`,\n");
        out.push_str("        # и без указания семейства nft отвергает загрузку всего файла.\n");
        for set_name in &vpn_sets {
            let _ = writeln!(
                out,
                "        ip daddr @{} meta l4proto {{ tcp, udp }} tproxy ip to :{} meta mark set {:#010x}",
                set_name, OPENSTREAM_TPROXY_PORT, OPENSTREAM_TPROXY_MARK
            );
        }
    }

    out.push_str("    }\n");

    // ------------------------------------------------- Цепочка filter forward
    // `reject` допустим только в input/forward/output — не в prerouting.
    if compiled.disable_quic || compiled.block_doh {
        out.push_str("\n    # Фильтрация протоколов. reject недопустим в prerouting — только здесь.\n");
        out.push_str("    chain filter_forward {\n");
        out.push_str("        type filter hook forward priority filter + 5; policy accept;\n");

        if has_clients {
            out.push_str("        ip saddr @bypass_clients return\n");
        }
        out.push_str("        ip daddr @bypass_targets return\n");
        out.push_str("        ip daddr @bypass_cidrs return\n");

        if compiled.disable_quic {
            out.push_str("        # Блокировка QUIC (UDP 443) — форсирует TCP TLS 1.3 для Zapret2\n");
            out.push_str("        udp dport 443 reject with icmpx type admin-prohibited\n");
        }

        if compiled.block_doh {
            out.push_str("        # Блокировка DoT (TCP 853) в обход локального резолвера\n");
            out.push_str("        tcp dport 853 reject with tcp reset\n");
        }

        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

/// Для обратной совместимости с тестами и модулями.
pub fn generate_nftables_sets(
    compiled: &CompiledRuleSet,
    table_family: &str,
    table_name: &str,
) -> String {
    generate_nftables_rules(compiled, table_family, table_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> CompiledRuleSet {
        let mut compiled = CompiledRuleSet::default();
        compiled
            .proxy_domains
            .push(("beta.crunchyroll.com".into(), "us_west".into()));
        compiled
            .zapret2_domains
            .push(("googlevideo.com".into(), "youtube_4k".into()));
        compiled.streamproxy_domains.push("live-video.net".into());
        compiled.bypass_p2p = true;
        compiled.bypass_clients.push("192.168.1.150".into());
        compiled
    }

    #[test]
    fn test_generate_nftables_rules_comprehensive() {
        let nft = generate_nftables_rules(&sample(), "inet", "openstream");

        assert!(nft.contains("table inet openstream {"));
        assert!(nft.contains("set bypass_cidrs {"));
        assert!(nft.contains("set bypass_p2p_ports {"));
        assert!(nft.contains("set bypass_clients {"));
        assert!(nft.contains("set zapret2_targets {"));
        assert!(nft.contains("set streamproxy_targets {"));
        assert!(nft.contains("set vpn_us_west {"));

        assert!(nft.contains("ip saddr @bypass_clients return"));
        assert!(nft.contains("queue num 1088 bypass"));
        assert!(nft.contains("tproxy ip to :10888"));
    }

    /// Квалификатор семейства в `tproxy` обязателен, когда правило содержит
    /// `ip daddr`: без него `nft` отвергает загрузку всего файла.
    /// Проверено на парсере: `nft -c -f`.
    #[test]
    fn test_tproxy_specifies_address_family() {
        let nft = generate_nftables_rules(&sample(), "inet", "openstream");
        assert!(nft.contains("tproxy ip to :10888"));
        assert!(!nft.contains("tproxy to :10888"));
    }

    /// `redirect` — NAT-statement и обязан находиться в цепочке type nat.
    /// Ранее он генерировался в type filter, из-за чего `nft -f` отвергал весь файл.
    #[test]
    fn test_redirect_lives_in_nat_chain_only() {
        let nft = generate_nftables_rules(&sample(), "inet", "openstream");

        let nat_chain = nft
            .split("chain nat_prerouting {")
            .nth(1)
            .and_then(|s| s.split("    }").next())
            .expect("цепочка nat_prerouting должна существовать");
        assert!(nat_chain.contains("type nat hook prerouting"));
        assert!(nat_chain.contains("redirect to :8888"));

        let mangle_chain = nft
            .split("chain mangle_prerouting {")
            .nth(1)
            .and_then(|s| s.split("    }").next())
            .expect("цепочка mangle_prerouting должна существовать");
        assert!(
            !mangle_chain.contains("redirect"),
            "redirect недопустим в цепочке type filter"
        );
    }

    /// `reject` допустим только в input/forward/output.
    #[test]
    fn test_reject_never_in_prerouting() {
        let mut compiled = sample();
        compiled.disable_quic = true;
        compiled.block_doh = true;
        let nft = generate_nftables_rules(&compiled, "inet", "openstream");

        let mangle_chain = nft
            .split("chain mangle_prerouting {")
            .nth(1)
            .and_then(|s| s.split("    }").next())
            .expect("цепочка mangle_prerouting должна существовать");
        assert!(
            !mangle_chain.contains("reject"),
            "reject недопустим в хуке prerouting"
        );

        assert!(nft.contains("chain filter_forward {"));
        assert!(nft.contains("type filter hook forward"));
        assert!(nft.contains("udp dport 443 reject"));
        assert!(nft.contains("tcp dport 853 reject"));
    }

    /// Невалидные значения из UCI не должны попадать в nft-файл (иначе ломается вся таблица).
    #[test]
    fn test_invalid_bypass_clients_are_filtered() {
        let mut compiled = CompiledRuleSet::default();
        compiled.bypass_clients.push("192.168.1.10".into());
        compiled.bypass_clients.push("10.0.0.0/8".into());
        compiled.bypass_clients.push("; rm -rf /".into());
        compiled.bypass_clients.push("not-an-ip".into());
        compiled.bypass_clients.push("999.999.999.999".into());

        let nft = generate_nftables_rules(&compiled, "inet", "openstream");

        assert!(nft.contains("192.168.1.10"));
        assert!(nft.contains("10.0.0.0/8"));
        assert!(!nft.contains("rm -rf"));
        assert!(!nft.contains("not-an-ip"));
        assert!(!nft.contains("999.999.999.999"));
    }

    #[test]
    fn test_no_bypass_clients_set_when_all_invalid() {
        let mut compiled = CompiledRuleSet::default();
        compiled.bypass_clients.push("garbage".into());

        let nft = generate_nftables_rules(&compiled, "inet", "openstream");
        assert!(!nft.contains("set bypass_clients"));
        assert!(!nft.contains("@bypass_clients"));
    }

    /// Петля sing-box предотвращается меткой, а не ct mark (ct mark нигде не ставился).
    #[test]
    fn test_loop_protection_uses_meta_mark() {
        let nft = generate_nftables_rules(&sample(), "inet", "openstream");
        assert!(nft.contains("meta mark & 0x00ff0000 == 0x00880000 return"));
        assert!(
            !nft.contains("ct mark &"),
            "ct mark нигде не устанавливается — проверка по нему никогда не срабатывала"
        );
    }

    #[test]
    fn test_gateway_set_name_sanitization() {
        assert_eq!(gateway_set_name("us_west"), "vpn_us_west");
        assert_eq!(gateway_set_name("us-west; drop"), "vpn_uswestdrop");
        assert_eq!(gateway_set_name(""), "vpn_default");
        assert_eq!(gateway_set_name("!!!"), "vpn_default");
    }

    /// Пустой набор правил не должен порождать цепочки со ссылками на несуществующие сеты.
    #[test]
    fn test_empty_ruleset_is_self_consistent() {
        let compiled = CompiledRuleSet::default();
        let nft = generate_nftables_rules(&compiled, "inet", "openstream");

        assert!(!nft.contains("@zapret2_targets"));
        assert!(!nft.contains("@streamproxy_targets"));
        assert!(!nft.contains("chain nat_prerouting"));
        assert!(nft.contains("@bypass_targets"));
    }
}
